image: Visual Studio 2017

environment:
  nuget_version: '2.9.0'
  nuget_prerelease: false
  assembly_version: '2.9.0.0'

deploy:
  - provider: GitHub
    description: |
      * .NET Core / .NET Standard support for NSubstitute, FakeItEasy and Moq.

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)
    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
        secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
        appveyor_repo_tag: true

clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

version: '$(nuget_version)+{build}'
configuration: Release

assembly_info:
  patch: true
  file: Source\**\Properties\AssemblyInfo.cs
  assembly_version: '$(assembly_version)'
  assembly_file_version: '$(assembly_version)'
  assembly_informational_version: '$(nuget_version)'

build_script:
- cmd: >-
    powershell -f build.ps1 -CodeDirectory "Source" -TestsDirectory "Source" -PackageOutputDirectory "Build" -Package "Machine.Fakes","Machine.Fakes.FakeItEasy","Machine.Fakes.Moq","Machine.Fakes.NSubstitute","Machine.Fakes.Rhinomocks" -Version "%NUGET_VERSION%" -Configuration "%CONFIGURATION%"
artifacts:
- path: **\Build\*.nupkg

test: off

