environment:
  nuget_version: '2.8.0-beta1'
  nuget_prerelease: true
  assembly_version: '2.8.0.0'

deploy:
  - provider: GitHub
    description: |
      * Support for .NET Standard 1.3 and NET Core. (only the Moq adaptor support .NET Standard)
      * Beta due to Machine.Specifications being in -rc1 and Moq for .NET Standard in alpha

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

  - provider: NuGet
    api_key:
        secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
        appveyor_repo_tag: true

clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

version: '$(nuget_version)+{build}'
configuration: Release

assembly_info:
  patch: true
  file: Source\**\Properties\AssemblyInfo.cs
  assembly_version: '$(assembly_version)'

build_script:
- cmd: >-
    powershell -f build.ps1 -CodeDirectory "Source" -TestsDirectory "Source" -PackageOutputDirectory "Build" -Package "Machine.Fakes","Machine.Fakes.Adapters.FakeItEasy","Machine.Fakes.Adapters.Moq","Machine.Fakes.Adapters.NSubstitute","Machine.Fakes.Adapters.Rhinomocks" -Version "%NUGET_VERSION%" -Configuration "%CONFIGURATION%"
artifacts:
- path: Build\*.nupkg

test: off

